### ISSUE TITLE
Improved read me file

### ISSUE THREAD

**Issue by Mistium** [Ninjaofbls/nOS#1]
Welcome to the nOS github repository.

nOS is a scratch based operating system that can run proprietary, preinstalled applications.

The os has a clean design, opting for a traditional start menu element on the bottom left corner of the os interface.

[My website](https://www.ninjaoofing.com)

Change log: 

v0.1.3 
- Relocated and more usable

**Comment by Ninjaofbl** [comment]
This is the Beta Version of the nOS. I am going to be updating it version and dimentings and startup in a future version. Remember it is that the first one is just a test. Also sorry is took awhile. I have been working on other things with life

**Comment by Mistium** [comment]
Yeah, no problem. I've been doing other stuff recently too. Excited to see where nOS goes!
